estados_finais = {
    'q3': 'tk_inicio',
    'q7': 'tk_fim',
    'q28': 'senao',
    'q9': 'se',
    'q15': 'tiponum',
    'q18': 'ler',
    'q25': 'escrever',
    'q33': 'enquanto',
    'q34': 'subtracao',
    'q35': 'adicao',
    'q36': 'mult',
    'q37': 'divisao',
    'q38': 'menor',
    'q40': 'maior',
    'q39': 'menorigual',
    'q41': 'maiorigual',
    'q42': 'atribuicao',
    'q43': 'igual',
    'q44': 'parenteses_abre',
    'q45': 'parenteses_fecha',
    'q46': 'chaves_abre',
    'q47': 'chaves_fecha',
    'q50': 'string',
    'q51': 'numero',
    'q52': 'id',
    'q53': 'fim_linha',
    'q54': 'espaco ou tabulacao'
}
