lista_producoes = {
    '0': ('<LISTA_COMANDOS>', ['<COMANDO>', '<LISTA_COMANDOS>']),
    '1': ('<LISTA_COMANDOS>', 'î'),
    '2': ('<FORMATO_PROGRAMA', ['tk_inicio', '<LISTA_COMANDOS>', 'tk_fim']),
    '3': ('<COMANDO>', ['escrever', 'parenteses_abre', '<ARGUMENTACAO>', 'parenteses_fecha', 'fim_linha']),
    '4': ('<COMANDO>', ['ler', 'parenteses_abre', 'id', 'parenteses_fecha', 'fim_linha']),
    '5': ('<COMANDO>', ['<DECLARACAO>', 'fim_linha']),
    '6': ('<COMANDO>', ['se', '<LOGICO>', 'chaves_abre', '<LISTA_COMANDOS>', 'chaves_fecha', '<SENAO>']),
    '7': ('<COMANDO>', ['enquanto', '<LOGICO>', 'chaves_abre', '<LISTA_COMANDOS>', 'chaves_fecha']),
    '8': ('<OPERADORES_MAT>', ['adicao']),
    '9': ('<OPERADORES_MAT>', ['subtracao']),
    '10': ('<OPERADORES_MAT>', ['mult']),
    '11': ('<OPERADORES_MAT>', ['divisao']),
    '12': ('<OPERADORES_LOGICOS>', ['maiorigual']),
    '13': ('<OPERADORES_LOGICOS>', ['menorigual']),
    '14': ('<OPERADORES_LOGICOS>', ['igual']),
    '15': ('<ARGUMENTACAO>', ['<STRING>']),
    '16': ('<ARGUMENTACAO>', ['<NUMERO>']),
    '17': ('<ARGUMENTACAO>', ['<VARIAVEL>']),
    '18': ('<STRING>', ['string']),
    '19': ('<NUMERO>', ['numero']),
    '20': ('<VARIAVEL>', ['id']),
    '21': ('<TIPO>', ['tiponum']),
    '22': ('<TIPO>', 'î'),
    '23': ('<DECLARACAO>', ['<TIPO>', 'id', '<ATRIBUICAO>']),
    '24': ('<ATRIBUICAO>', ['atribuicao', '<CALCULO>']),
    '25': ('<ATRIBUICAO>', 'î'),
    '26': ('<OPERANDO>', ['<NUMERO>']),
    '27': ('<OPERANDO>', ['<VARIAVEL>']),
    '28': ('<CALCULO>', ['<OPERANDO>', '<EXPRESSAO>']),
    '29': ('<CALCULO>', ['parenteses_abre', '<CALCULO>', 'parenteses_fecha', '<EXPRESSAO>']),
    '30': ('<EXPRESSAO>', ['<OPERADORES_MAT>', '<CALCULO>']),
    '31': ('<EXPRESSAO>', 'î'),
    '32': ('<LOGICO>', ['parenteses_abre', '<EXPRESSAO_LOGICA>', 'parenteses_fecha']),
    '33': ('<EXPRESSAO_LOGICA>', ['<CALCULO>', '<OPERADORES_LOGICOS>', '<CALCULO>']),
    '34': ('<SENAO>', ['senao', 'chaves_abre', '<LISTA_COMANDOS>', 'chaves_fecha']),
    '35': ('<SENAO>', 'î')
}
